version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: gestorHospital
    ports:
      - "8081:80"
    volumes:
      - ./Frontend:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network-p4
    restart: always

  db:
    image: postgres:15-alpine
    container_name: DBProyecto_PG
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: host
      POSTGRES_DB: Hospital
    ports:
      - "5433:5432"
    volumes:
      - postgres-data-p4:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    networks: 
      - app-network-p4
    restart: always

  backend:
    build: ./Backend
    container_name: API_Hospital
    ports:
      - "8008:8000"
    volumes:
      - ./Backend:/app
    depends_on:
      - db
    networks:
      - app-network-p4
    restart: always

networks:
  app-network-p4:
    driver: bridge

volumes:
  postgres-data-p4:
    driver: local